# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knj5Qv5xdRtNl7yyNYWJdWv03MjontNW
"""

import pandas as pd
teacher=pd.DataFrame({
    'Ism':['Durbek','Sarvinoz'],
    'Familya': ['Xalilov','Toxirova'],
    'Fan': ['Suniy Intilek','Suniy Intilek'],
    'Telefon raqami': ['+998991234567','+998991234567'],
    'Ish joyi': ['TATU FF','TATU FF']
})
print(teacher)
teacher.to_excel('teacher.xlsx',index=False,sheet_name='Sheet1')